security:
    providers:
        external_users:
            id: App\Security\ExternalUserProvider
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            pattern: ^/api
            stateless: true
            provider: external_users
            access_token:
                token_handler:
                    id: App\Security\ExternalAccessTokenHandler
        main:
            lazy: true
            provider: external_users
            entry_point: App\Security\ExternalLoginAuthenticator
            custom_authenticators:
                - App\Security\ExternalLoginAuthenticator
            logout:
                path: app_logout
                target: app_login

    access_control:
        - { path: '^/login$', roles: PUBLIC_ACCESS }
        - { path: '^/logout$', roles: PUBLIC_ACCESS }
        - { path: '^/json/[A-Za-z0-9]{5}$', roles: PUBLIC_ACCESS }
        - { path: '^/print/[A-Za-z0-9]{5}$', roles: PUBLIC_ACCESS }
        - { path: '^/upgrade/[A-Za-z0-9]{5}$', roles: PUBLIC_ACCESS }
        - { path: '^/[A-Za-z0-9]{5}$', roles: PUBLIC_ACCESS }
        - { path: '^/app/api', roles: ROLE_EXTERNAL_USER }
        - { path: '^/api', roles: ROLE_EXTERNAL_USER }
        - { path: '^/settings/hotels$', roles: ROLE_EXTERNAL_USER }
        - { path: '^/$', roles: ROLE_EXTERNAL_USER }
